# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-31 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='resolved',
        ),
    ]
